# Generated by Django 6.0.3 on 2026-03-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_order_id',
            new_name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='UPI', max_length=50),
        ),
    ]
