# Generated by Django 6.0.3 on 2026-03-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_book_lending_price_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AddField(
            model_name='book',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AddField(
            model_name='book',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AddField(
            model_name='book',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AddField(
            model_name='book',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
    ]
